name: CI/CD Innovatech Deploy

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    name: Construir y Subir a ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Iniciar sesión en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 1. CONSTRUIR Y SUBIR BACK-VENTAS
      - name: Build y Push Back-Ventas
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: innovatech-ep2-back-ventas
          IMAGE_TAG: latest
        run: |
          cd backend/back-Ventas_SpringBoot
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile ./Springboot-API-REST
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # 2. CONSTRUIR Y SUBIR BACK-DESPACHOS
      - name: Build y Push Back-Despachos
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: innovatech-ep2-back-despachos
          IMAGE_TAG: latest
        run: |
          cd backend/back-Despachos_SpringBoot
          # Nota: Asumo que Despachos tiene la misma estructura. Si no tiene la subcarpeta, me avisas al tiro.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile ./Springboot-API-REST
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG